### PR TITLE
New upstream release (0.7.0)

### PR DESCRIPTION
**Pull request by sbadia**
Build consul debian packages v0.7.0 (refs: #11 )

### CODE REVIEW

**Comment by corny** [comment]
@bcandrea Can help to finish the packages for v0.7.0?

**Comment by corny** [comment]
@bcandrea PING

**Comment by DamionWaltermeyer** [comment]
*bump*  How about updating this?  thanks.

**Comment by sbadia** [comment]
Yep, 0.7.1 is relased now, I'll take a look

**Comment by bcandrea** [comment]
Closing as I built 0.7.1 just now. I can't manage to submit the binaries for Yakkety to Launchpad for some reason, but they can be built using this repo.

**Comment by sbadia** [comment]
Thanks @bcandrea !!
What the issue with Yakkety/PPA, can I help?

**Comment by bcandrea** [comment]
Well, the problem lies in the fact that building the orig.tar.gz seems to be done differently from within the yakkety docker image, and results in a slightly different tarball. On submission launchpad detects the difference and rejects the package. I might start to consider building a 'golden' original tarball externally and feed it to git-buildpackage  (I already tried with not too much luck). Anyway, the process for releasing a new version is too long and tedious, so I definitely need an automated way of doing it. As always, suggestions welcome :)

**Pull request closed without merging**
